name: parksy_audio_tools
description: Audio trimmer + MIDI converter for personal use
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  # Shared
  file_picker: ^8.0.0
  path_provider: ^2.1.1
  share_plus: ^7.2.1
  # Trimmer
  just_audio: ^0.9.36
  ffmpeg_kit_flutter_audio: ^6.0.3
  intl: ^0.19.0
  # Converter
  dio: ^5.4.0
  permission_handler: ^11.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
