name: parksy_axis
description: Broadcast stage position overlay - Pro Edition
publish_to: 'none'
version: 7.3.1+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_overlay_window: ^0.5.0
  shared_preferences: ^2.2.2
  # path_provider 제거 - v7.3에서 하드코딩 경로 사용

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
